# Путь для файлов кэша nginx
proxy_cache_path /var/cache/nginx/directus_assets 
                 levels=1:2 
                 keys_zone=directus_assets:50m 
                 max_size=2g 
                 inactive=30d 
                 use_temp_path=off;

# HTTPS без www
server {
    server_name cms.yourdomain.ru;

    client_max_body_size 5M; # ограничение размера на загрузку файлов в админке directus

    # Кэш для изображений
    location /assets/ {
        proxy_pass http://localhost:8055;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_cache directus_assets;
        proxy_cache_valid 200 30d;
        proxy_cache_valid 404 1m;
        proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
        proxy_cache_background_update on;
        proxy_cache_lock on;

        proxy_ignore_headers Set-Cookie Cache-Control;
        proxy_hide_header Set-Cookie;

        add_header X-Cache-Status $upstream_cache_status always;
        add_header Alt-Svc 'h3=":443"; ma=86400' always;
    }

    location / {
        proxy_pass http://localhost:8055;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        add_header Alt-Svc 'h3=":443"; ma=86400' always;
    }

    listen 443 ssl;
    listen 443 quic reuseport;
    http2 on;
    ssl_certificate /etc/letsencrypt/live/yourdomain.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/yourdomain.ru/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

# Редирект с HTTPS www на HTTPS без www
server {
    listen 443 ssl;
    listen 443 quic;
    server_name www.cms.yourdomain.ru;
    
    add_header Alt-Svc 'h3=":443"; ma=86400' always;

    ssl_certificate /etc/letsencrypt/live/yourdomain.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/yourdomain.ru/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    return 301 https://cms.yourdomain.ru$request_uri;
}

# Редирект с HTTP на HTTPS без www
server {
    listen 80;
    listen [::]:80;
    server_name cms.yourdomain.ru www.cms.yourdomain.ru;

    return 301 https://cms.yourdomain.ru$request_uri;
}