server {
    server_name cms.yourdomain.ru;

    client_max_body_size 5M; # ограничение размера на загрузку файлов в админке Directus

    location / {
        proxy_pass http://localhost:8055;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        add_header Alt-Svc 'h3=":443"; ma=86400' always;
    }


    listen 443 ssl;
    listen 443 quic reuseport;
    http2 on;
    ssl_certificate /etc/letsencrypt/live/yourdomain.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/yourdomain.ru/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

}server {
    if ($host = cms.yourdomain.ru) {
        return 301 https://$host$request_uri;
    }

    server_name cms.yourdomain.ru;
    listen 80;
    return 404;

}